# Generated by Django 4.1 on 2023-02-11 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BudgetObjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view', 'Can view budget objects'), ('can_manage', 'Can manage budget objects')],
                'unique_together': {('budget_name', 'created_by')},
            },
        ),
    ]
